### ISSUE TITLE
ES 5 version?

### ISSUE THREAD

**Issue by upeshdesai** [vincentjames501/angular-cron-gen#1]
Hello, great work on this! I was wondering if it would be possible to create a ES 5 version?

**Comment by vincentjames501** [comment]
The source is compiled to ES5 compliant code through babel. Is that not what you need in build?

https://github.com/vincentjames501/angular-cron-gen/tree/master/build

**Comment by upeshdesai** [comment]
Ah yes, I didn't correctly state my question. In the project I'm working on, we use gulp-uglify to minify files, but it does not work with already minified files which is where my issue arises. If it's not too difficult, is there a way to use babel to just convert to the full .js file? I've been trying to use babel myself to do it within my project but to no avail

**Comment by upeshdesai** [comment]
Nevermind, we've resolved this. Thank you!
