### ISSUE TITLE
Is a shim needed for IE 11 support in versions after 0.20?

### ISSUE THREAD

**Issue by c0pp3rt0p** [vincentjames501/angular-cron-gen#14]
In cron-gen.module.js  IE 11 throws an error "Object doesn't support property or method 'keys'" when setting up the SELECT_OPTIONS object.  Is a shim needed to support the keys property?  Seems the demo doesn't work under IE either but could be a bad setting on my part.

**Comment by vincentjames501** [comment]
Crap. Yeah. Looks like a shim is required. I'd rather work around Object.keys and just do it old school. Want to submit a pull request?

**Comment by vincentjames501** [comment]
Or maybe it's Array.keys, haven't actually loaded it up in IE11.

**Comment by c0pp3rt0p** [comment]
Yup, I can submit a pull request.  I prefer the old school option as well. I believe I'll need to be added.

**Comment by c0pp3rt0p** [comment]
As a followup, I'm 90% sure I had the .20 version working in ie which appears to use the array.keys property as well.

**Comment by vincentjames501** [comment]
Fixed by #15
