### ISSUE TITLE
use24HourTime option is causing ngForm to be invalid

### ISSUE THREAD

**Issue by ghost** [vincentjames501/angular-cron-gen#19]
Hi. Great plugin. I use it inside `<form>` with Angular Validation.

With **use24HourTime** option the AM/PM selector is hidden. And that's what I see in HTML:
![](https://i.imgur.com/m4ub8v2.png)

It is hidden but it is also required and it has no default value, because of that my form is invalid.
```
{
  "$error": {
    "required": [
      {
        "$viewValue": null,
        "$validators": {},
        "$asyncValidators": {},
        "$parsers": [],
        "$formatters": [],
        "$viewChangeListeners": [
          null
        ],
        "$untouched": true,
        "$touched": false,
        "$pristine": true,
        "$dirty": false,
        "$valid": false,
        "$invalid": true,
        "$error": {
          "required": true
        },
        "$name": "HourType",
        "$options": null
      }
    ]
  },
  "$name": "$ctrl.form",
  "$dirty": true,
  "$pristine": false,
  "$valid": false,
  "$invalid": true,
  "$submitted": false,
....
```

 Any way to fix this? Thanks.

**Comment by vincentjames501** [comment]
I imagine an `ng-if` vs `ng-show` on those elements would do the trick though there is still another issue that the regex used to determine if the form is valid isn't 100% accurate.

**Comment by amouhoub** [comment]
@vincentjames501  could be solved by https://github.com/vincentjames501/angular-cron-gen/pull/49
