### ISSUE TITLE
Unneeded dependency to Symbol

### ISSUE THREAD

**Issue by FritzHerbers** [vincentjames501/angular-cron-gen#2]
I think the dependency to Symbol is unneeded. 
It took too long for me to figure out what I exactly need to incorporate it in my application. At the end I adapted the source:

    var States = {
        INIT: 1, // Symbol('INIT'),
        DIRTY: 2, // Symbol('DIRTY'),
        CLEAN: 3 // Symbol('CLEAN')
    };

I don't think you win something to be cutting-edge using Symbol.
Having a library with as few dependencies as possible is always the best.

**Comment by vincentjames501** [comment]
PRs welcome :). If I don't get one I'll fix then when I get back from vacation.
