### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by claudiuconstantin** [vincentjames501/angular-cron-gen#22]
It would be nice if we could use the library with Angular 2+. Any plans of upgrading? Would you accept a PR for this?

**Comment by claudiuconstantin** [comment]
I [forked](https://github.com/claudiuconstantin/cron-editor) the project and moved on, you can close this.

**Comment by vincentjames501** [comment]
I would accept a PR for this so long as it remained compatible with Angular 1.5+. Sorry for not responding until now!
