### ISSUE TITLE
From server side perspective

### ISSUE THREAD

**Issue by dbrezoev** [vincentjames501/angular-cron-gen#30]
Sorry for asking here. 
Which node js library fits best with this cron generator?
I need it to accept the generated cron and execute the task on the backend. 
Thanks in advance

**Comment by vincentjames501** [comment]
We use a Java backend and we use Quartz. I imagine any node library that can parse a Quartz expression should do the trick. Check out https://www.npmjs.com/browse/keyword/quartz. I also imagine it wouldn't be hard to convert this project to generate UNIX cron expressions which should make it more trivial to integrate with other node scheduling systems.
