### ISSUE TITLE
How can we add the same functionality in angular-2 or angular-4.Please help 

### ISSUE THREAD

**Issue by bindu1552** [vincentjames501/angular-cron-gen#31]
How can we convert the same functionality to angular-2.

**Comment by vincentjames501** [comment]
There is an active fork of this project for Angular 2+ [here](https://github.com/claudiuconstantin/cron-editor). I will not be updating this project to support Angular 2+, just maintaining it for Angular 1.X.

**Comment by bindu1552** [comment]
Thank You for your replay.

while installing getting the below issue:

"ERROR in CronEditorModule is not an NgModule"

**Comment by bindu1552** [comment]
getting the below error:

0] ERROR in c:/NEERCompliance/complianceapp/ComplianceApp.Web/client
-app/app/control-administration/schedule/cron-editor/cron-editor.comp
onent.ts (8,15): Cannot find name 'require'.
[0] ERROR in c:/NEERCompliance/complianceapp/ComplianceApp.Web/client
-app/app/control-administration/schedule/cron-editor/cron-editor.comp
onent.ts (9,14): Cannot find name 'require'.
[0] ERROR in c:/NEERCompliance/complianceapp/ComplianceApp.Web/client
-app/app/control-administration/schedule/cron-editor/cron-time-picker
.component.ts (5,15): Cannot find name 'require'.
[0] ERROR in CronEditorMo

**Comment by vincentjames501** [comment]
Please log this bug in the Angular 2 fork.

**Comment by claudiuconstantin** [comment]
@bindu1552, check out this [issue](https://github.com/claudiuconstantin/cron-editor/issues/2), the problem will be discussed there
