### ISSUE TITLE
How to use it without bootstrap?

### ISSUE THREAD

**Issue by vsspt** [vincentjames501/angular-cron-gen#33]
I've followed the instructions on the README.md:

> 1. Include the dependency in your app

```
angular.module('myApp', ['angular-cron-gen'])
```

> 2. Include  the supplied JS and CSS file (or create your own CSS to override defaults).

```
<link rel='stylesheet' href='build/cron-gen.min.css' type='text/css' media='all' /> 
<script type='text/javascript' src='build/cron-gen.min.js'></script>
```

Nevertheless, although the Widget appear, the layout is totally incorrect, indicating some problem with the CSS. Only when including the Bootstrap CSS the widget appears as in the Demo page.
Unfortunately, we cannot use the Bootstrap CSS, so i would like to know if the Widget only works correctly when including the Bootstrap CSS, or if there is a way to use it without it.

Regards, and thank you for your excellent widget.

**Comment by vincentjames501** [comment]
You can do a few things. You can completely use your own custom template:

`template-url="your optional, custom template (Defaults to a bootstrap 3 template)"`

Or you can override some of the classes to make it look like what you want:

``` 
      formInputClass: 'form-control cron-gen-input', // Form input class override
      formSelectClass: 'form-control cron-gen-select', // Select class override
      formRadioClass: 'cron-gen-radio', // Radio class override
      formCheckboxClass: 'cron-gen-checkbox', // Radio class override
```

Unfortunately I don't have any vanilla css templates that could be used at the moment but would gladly accept a PR!

**Comment by vsspt** [comment]
Thank you very much for your quick response.
