### ISSUE TITLE
hideAdvancedTab still displays the Advanced tab

### ISSUE THREAD

**Issue by zeineb** [vincentjames501/angular-cron-gen#35]
$scope.cronOptions = {
     ...
      hideMinutesTab: false, 
      hideHourlyTab: false, 
      hideDailyTab: false, 
      hideWeeklyTab: false, 
      hideMonthlyTab: false, 
      hideYearlyTab: true,
      hideAdvancedTab: true,
      use24HourTime: false, 
      hideSeconds: true 
    };

And I still get the advanced tab: 
<img width="546" alt="capture d ecran 2018-04-05 a 16 10 36" src="https://user-images.githubusercontent.com/368264/38371118-f2af24b2-38eb-11e8-9e00-dbb73f51c720.png">

**Comment by vincentjames501** [comment]
I'd happily accept a PR though I am surprised by this as we use this in our application and disable the advanced tab all the time.

**Comment by vincentjames501** [comment]
I can't seem to reproduce this issue. Can you post a fiddle and we can reopen? Thanks!
