### ISSUE TITLE
Adopt with Angular 1.4+

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [vincentjames501/angular-cron-gen#37]
We are using ng 1.4.8 in our company and as far as our product consist of several big modules it is not possible for us to migrate ng to higher version right now. So I was thinking to change source code of angular-cron-gen to adopt it to ng 1.4.

I checked source code of angular-cron-gen and find out the most used feature of ng 1.5 is components instead of directives. Is there any other feature of ng 1.5 used that I should change? any other suggestion appreciated.

**Comment by vincentjames501** [comment]
I think components are the big one.

**Comment by ImanMahmoudinasab** [comment]
Unlike components As there is no such a `$onInit(){...}` method in the controller of directives where is the best place to call the method in a directive manually?

https://github.com/vincentjames501/angular-cron-gen/blob/f3a288580c5dfde168d631ebd5e9db880b9265d0/src/cron-gen.component.js#L166-L171

**Comment by ImanMahmoudinasab** [comment]
I have moved the codes in `$onInit(){...}` method to link function of the directive and it works like a charm! I finished adopting angular-cron-gen to ng 1.4 and I have tested anything possible. it's done!
