### ISSUE TITLE
use24HourTime option does not refresh the model correctly

### ISSUE THREAD

**Issue by ascott42** [vincentjames501/angular-cron-gen#47]
Hello

If we set the `use24HourTime` option to `true`, the model is not correctly refreshed.
For example, if you set `every day at 22`, you will reload with `every day at 10`.

You could see the bug here :
http://jsfiddle.net/ascott42/w5dzge1f/6/

The `ngModel ` watcher is triggered before the option watcher that's why the model is not computed with the 24 hour time format.
I fix it by recomputing the model every time options change, but this is not a very optimized solution (the cron is now analyzed two times).

```
// Watch for option changes
        $scope.$watch('$ctrl.options', function (options) {
            _this.parsedOptions = _this.mergeDefaultOptions(options);
            return _this.handleModelChange(_this.ngModel);
        }, true);
```
I'm interested in your opinion on this
Thanks

**Comment by vincentjames501** [comment]
I'd be happy to accept a PR here

**Comment by medou-boushab** [comment]
@ascott42  I have the same issue, did you fix it?

**Comment by vincentjames501** [comment]
Happy accept a PR!

**Comment by medou-boushab** [comment]
@vincentjames501 here my [PR](https://github.com/vincentjames501/angular-cron-gen/pull/49)
