### ISSUE TITLE
Seconds Field

### ISSUE THREAD

**Issue by JHouck1230** [vincentjames501/angular-cron-gen#6]
I installed this via bower specifically for the supported quartz cron format. But the "seconds" field is missing from the bower install.

`bower i --save angular-cron-gen`

![angular cron gen](https://cloud.githubusercontent.com/assets/13889311/20976345/3e3096ea-bc70-11e6-8958-c50a4f1e18cd.png)

I'm using all the default settings plus the advanced tab.

`$scope.cronExpression = '0 0 0/3 1/1 * ? *';
$scope.isCronDisabled = false;
$scope.cronOptions = {
formInputClass: 'form-control cron-gen-input',
formSelectClass: 'form-control cron-gen-select',
formRadioClass: 'form-control-static cron-gen-radio',
formCheckboxClass: 'form-control-static cron-gen-checkbox',
hideMinutesTab: false,
hideHourlyTab: false,
hideDailyTab: false,
hideWeeklyTab: false,
hideMonthlyTab: false,
hideYearlyTab: false,
hideAdvancedTab: false,
use24HourTime: false,
hideSeconds: false
}`

Based on the repo is should exist, but I cannot find it in the installed package. Is there something I'm doing incorrectly?

**Comment by vincentjames501** [comment]
Maybe it's not finding our options? Can you supply more of a code sample so I can help debug?

**Comment by JHouck1230** [comment]
This is the only element in the body:

`	<div class="container">
		<cron-gen ng-model="cronExpression" 
	          options="cronOptions" 
	          ng-disabled="isCronDisabled">
		</cron-gen>
	</div>`

And this is the entirety of the JavaScript:
'use strict';

angular.module('app', ['angular-cron-gen'])
	.controller('mainCtrl', function($scope) {
		$scope.cronExpression = '0 0 0/3 1/1 * ? *';
    $scope.isCronDisabled = false;
    $scope.cronOptions = {
      formInputClass: 'form-control cron-gen-input',
      formSelectClass: 'form-control cron-gen-select',
      formRadioClass: 'form-control-static cron-gen-radio',
      formCheckboxClass: 'form-control-static cron-gen-checkbox',
      hideMinutesTab: false,
      hideHourlyTab: false,
      hideDailyTab: false,
      hideWeeklyTab: false,
      hideMonthlyTab: false,
      hideYearlyTab: false,
      hideAdvancedTab: false,
      use24HourTime: false,
      hideSeconds: false
		}
});


There are no errors in the console. This is the script load order:

`<script src="/bower_components/jquery/dist/jquery.min.js"></script>
	<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="/bower_components/angular/angular.min.js"></script>
	<script src="/bower_components/angular-cron-gen/build/cron-gen.min.js"></script>
	<script src="module.js"></script>`

**Comment by JHouck1230** [comment]
Upon further troubleshooting, it seems an installation from npm/bower does not have the seconds field. Cloning the repo directly has everything though.

**Comment by vincentjames501** [comment]
I just published 0.0.21. Hopefully that fixes it for you.
