### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by c0pp3rt0p** [vincentjames501/angular-cron-gen#9]
IE doesn't support the use of the Symbol function used in cron-gen.js.  :(

**Comment by vincentjames501** [comment]
Yeah, it was removed in PR #5 . I believe I've republished the library, no?

**Comment by c0pp3rt0p** [comment]
You are correct, I was using bower and the latest code there looks to be 0.0.20.

**Comment by vincentjames501** [comment]
Pushed 0.0.21
